docker pull docker.xuanyuan.run/kolla/neutron-server:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/neutron-l3-agent:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/neutron-metadata-agent:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/neutron-dhcp-agent:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/neutron-openvswitch-agent:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/keystone:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/keystone-fernet:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/keystone-ssh:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/nova-novncproxy:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/placement-api:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/nova-scheduler:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/nova-conductor:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/nova-api:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/glance-api:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/heat-api:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/heat-api-cfn:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/heat-engine:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/horizon:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/kolla-toolbox:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/mariadb-server:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/openvswitch-vswitchd:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/openvswitch-db-server:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/rabbitmq:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/memcached:2024.1-ubuntu-jammy
docker pull docker.xuanyuan.run/kolla/cron:2024.1-ubuntu-jammy
